spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supportsaas
    username: supportsaas
    password: supportsaas
    hikari:
      maximum-pool-size: 22
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.leonardtrinh.supportsaas: DEBUG
    org.springframework.security: DEBUG
