spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
  flyway:
    locations: classpath:db/migration

logging:
  level:
    root: WARN
    com.leonardtrinh.supportsaas: INFO
